### ISSUE TITLE
New Alnitak generic command

### ISSUE THREAD

**Issue by tlkw79** [jwellman80/ArduinoLightbox#3]
Hi Jared, 

Really hope you can update the command so that other Softwares also can connect with it. I tried your Arduino firmware recently and it failed to connect in NINA, SGpro and so on. 

Hope to hear from you soon. 

Regards,
Tom

**Comment by jwellman80** [comment]
Working well with the Uno and SGP.  The Leonardo needs to have the RTS and DTR set differently from the calling application.  The SGP implementation is geared towards the Alnitak FlipFlat device.  I'd recommend switching your device to an Uno or similar Arduino that uses the ATmega328 rather than the ATmega32u4.  

Thank you,
Jared
